blank_issues_enabled: false

issue_templates:
  - name: "🐞 Bug Report"
    description: "Signaler un bug reproductible"
    path: "bug_report.md"

  - name: "🚀 Feature Request"
    description: "Proposer une nouvelle fonctionnalité"
    path: "feature_request.md"

  - name: "📌 Task"
    description: "Créer une tâche technique ou de maintenance"
    path: "task.md"

  - name: "🛠️ Improvement"
    description: "Proposer une amélioration ou optimisation"
    path: "improvement.md"
